apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: frontend-deployment
  template:
    metadata:
      labels:
        app: frontend-deployment
    spec:
      containers:
      - name: app
        image: alpine
        command: ["tail", "-f", "/dev/null"]
        ports:
        - name: http
          containerPort: 80
