apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      containers:
      - name: "oooo"
        image: tenent1-image:tag
        ports:
        - name: http
          containerPort: 9911
        command: ["tail", "-f", "/dev/null"]
